language: r
cache: packages
pandoc_version: 2.5
r_github_packages: r-lib/remotes#340

install:
  - R -e 'install.packages(c("rmarkdown", "leaflet", "shiny"))'

script:
Rscript -e "rmarkdown::render_site()"
set -e

[ -z "${GITHUB_PAT}" ] && exit 0
[ "${TRAVIS_BRANCH}" != "main" ] && exit 0

git config --global user.email "leg.ifgoiano@gmail.com"
git config --global user.name "leg-ifgoiano"

git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git site
cd site
cp -r ../docs/* ./
git add --all *
git commit -m "launching 1" || true
git push -q origin gh-pages
