language: r
cache: packages
pandoc_version: 2.5
r_github_packages: r-lib/remotes#340

install:
  - R -e 'install.packages(c("rmarkdown", "devtools", "leaflet", "shiny"))'

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
