---
title: " "
runtime: shiny
output:
  html_document:
    toc: false
---

```{r, include=FALSE, message=FALSE}
library(EBImage)
library(shiny)
```

```{r echo=FALSE}
source("functions_leafshape.r")
```

```{r echo=FALSE}
# --------------------------- server
   img <- reactive({
      f <- input$image
      if (is.null(f)) return(NULL) else readImage(f$datapath)
   })
# ------------------------- ui
fluidPage(
   titlePanel("The Leaf Shape App"),
   sidebarLayout(
      sidebarPanel(
         fileInput("image", label = "Select image (.JPG or .TIF)"),
         br(),
         h6("Powered by:"),
         tags$img(src = "imagens/LEG_logo.png", heigth = 110, width = 110)
      ),
   mainPanel(
      tabsetPanel(
         tabPanel("Image raster", 
                  renderPlot({
                    req(img())
                    plot(img(), all=FALSE)
                    })
                  ),
         tabPanel("Leaf shape", 
                  renderPlot({
                    s1 <- identifyShape(path = input$image$datapath)
                    plot(s1$borders, type = "l", asp = 1, xlab = "", ylab = "")
                    polygon(s1$borders[, 1], s1$borders[,2], col = adjustcolor("green", 0.2))
                    })
                  )
         )
      )
   )
)
```
